// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2024-07-23 10:03:51
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// OptimizeForHDL: on
// HDLSynthTool: Vivado
// HDLSynthCmd: add_file $src_dir/%s\n
// HDLSynthFilePostfix: _vivado.tcl
// HDLSynthInit: set src_dir [pwd]\nset prj_dir "vivado_prj"\nfile mkdir ../$prj_dir\ncd ../$prj_dir\ncreate_project %s.xpr\nset_property PART xc7vx485tffg1761-1 [current_project]\n
// HDLSynthTerm: launch_runs synth_1 -force\nwait_on_run synth_1\n
// TargetDirectory: hdlsrc_484.4961_4th
// AddInputRegister: off
// AddOutputRegister: off
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// ClockHighTime: 3906.25
// ClockLowTime: 3906.25
// InitializeTestBenchInputs: on
// LoopUnrolling: on

// Filter Specifications:
//
// Sample Rate            : N/A (normalized frequency)
// Response               : Bandstop
// Specification          : Fp1 47.07,Fst1 48.07,Fst2 52.07,Fp2 53.07,Ap1 2,Ast 5,Ap2 2
// Second Passband Edge   : 0.21907
// First Passband Ripple  : 2 dB
// First Stopband Edge    : 0.19843
// First Passband Edge    : 0.1943
// Stopband Atten.        : 5 dB
// Second Passband Ripple : 2 dB
// Second Stopband Edge   : 0.21494
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 2
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s16,14 -> [-2 2)
// Denominator         : s16,14 -> [-2 2)
// Scale Values        : s16,15 -> [-1 1)
// Input               : s16,0 -> [-32768 32768)
// Section Input       : s16,10 -> [-32 32)
// Section Output      : s16,11 -> [-16 16)
// Output              : s16,0 -> [-32768 32768)
// State               : s16,15 -> [-1 1)
// Numerator Prod      : s32,29 -> [-4 4)
// Denominator Prod    : s32,29 -> [-4 4)
// Numerator Accum     : s40,29 -> [-1024 1024)
// Denominator Accum   : s40,29 -> [-1024 1024)
// Round Mode          : convergent
// Overflow Mode       : wrap
// Cast Before Sum     : true
// -------------------------------------------------------------
// Multipliers           : 8



`timescale 1 ns / 1 ns

module filter_2
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16
  output  signed [15:0] filter_out; //sfix16

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] scaleconst1 = 16'b0111110100100001; //sfix16_En15
  parameter signed [15:0] coeff_b1_section1 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section1 = 16'b1001100111111001; //sfix16_En14
  parameter signed [15:0] coeff_b3_section1 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section1 = 16'b1001111000010010; //sfix16_En14
  parameter signed [15:0] coeff_a3_section1 = 16'b0011110100010100; //sfix16_En14
  parameter signed [15:0] scaleconst2 = 16'b0111110100100001; //sfix16_En15
  parameter signed [15:0] coeff_b1_section2 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section2 = 16'b1001100111111001; //sfix16_En14
  parameter signed [15:0] coeff_b3_section2 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section2 = 16'b1001101010000001; //sfix16_En14
  parameter signed [15:0] coeff_a3_section2 = 16'b0011110100111110; //sfix16_En14
  // Signals
  wire signed [15:0] input_typeconvert; // sfix16
  wire signed [42:0] scale1; // sfix43_En26
  wire signed [31:0] mul_temp; // sfix32_En15
  wire signed [15:0] scaletypeconvert1; // sfix16_En10
  // Section 1 Signals 
  wire signed [39:0] a1sum1; // sfix40_En29
  wire signed [39:0] a2sum1; // sfix40_En29
  wire signed [39:0] b1sum1; // sfix40_En29
  wire signed [39:0] b2sum1; // sfix40_En29
  wire signed [15:0] typeconvert1; // sfix16_En15
  reg  signed [15:0] delay_section1 [0:1] ; // sfix16_En15
  wire signed [39:0] inputconv1; // sfix40_En29
  wire signed [31:0] a2mul1; // sfix32_En29
  wire signed [31:0] a3mul1; // sfix32_En29
  wire signed [31:0] b2mul1; // sfix32_En29
  wire signed [39:0] sub_cast; // sfix40_En29
  wire signed [39:0] sub_cast_1; // sfix40_En29
  wire signed [40:0] sub_temp; // sfix41_En29
  wire signed [39:0] sub_cast_2; // sfix40_En29
  wire signed [39:0] sub_cast_3; // sfix40_En29
  wire signed [40:0] sub_temp_1; // sfix41_En29
  wire signed [39:0] b1multypeconvert1; // sfix40_En29
  wire signed [39:0] add_cast; // sfix40_En29
  wire signed [39:0] add_cast_1; // sfix40_En29
  wire signed [40:0] add_temp; // sfix41_En29
  wire signed [39:0] add_cast_2; // sfix40_En29
  wire signed [39:0] add_cast_3; // sfix40_En29
  wire signed [40:0] add_temp_1; // sfix41_En29
  wire signed [15:0] section_result1; // sfix16_En11
  wire signed [42:0] scale2; // sfix43_En26
  wire signed [31:0] mul_temp_1; // sfix32_En26
  wire signed [15:0] scaletypeconvert2; // sfix16_En10
  // Section 2 Signals 
  wire signed [39:0] a1sum2; // sfix40_En29
  wire signed [39:0] a2sum2; // sfix40_En29
  wire signed [39:0] b1sum2; // sfix40_En29
  wire signed [39:0] b2sum2; // sfix40_En29
  wire signed [15:0] typeconvert2; // sfix16_En15
  reg  signed [15:0] delay_section2 [0:1] ; // sfix16_En15
  wire signed [39:0] inputconv2; // sfix40_En29
  wire signed [31:0] a2mul2; // sfix32_En29
  wire signed [31:0] a3mul2; // sfix32_En29
  wire signed [31:0] b2mul2; // sfix32_En29
  wire signed [39:0] sub_cast_4; // sfix40_En29
  wire signed [39:0] sub_cast_5; // sfix40_En29
  wire signed [40:0] sub_temp_2; // sfix41_En29
  wire signed [39:0] sub_cast_6; // sfix40_En29
  wire signed [39:0] sub_cast_7; // sfix40_En29
  wire signed [40:0] sub_temp_3; // sfix41_En29
  wire signed [39:0] b1multypeconvert2; // sfix40_En29
  wire signed [39:0] add_cast_4; // sfix40_En29
  wire signed [39:0] add_cast_5; // sfix40_En29
  wire signed [40:0] add_temp_2; // sfix41_En29
  wire signed [39:0] add_cast_6; // sfix40_En29
  wire signed [39:0] add_cast_7; // sfix40_En29
  wire signed [40:0] add_temp_3; // sfix41_En29
  wire signed [15:0] output_typeconvert; // sfix16

  // Block Statements
  assign input_typeconvert = filter_in;

  assign mul_temp = input_typeconvert * scaleconst1;
  assign scale1 = $signed({mul_temp[31:0], 11'b00000000000});

  assign scaletypeconvert1 = (scale1[31:0] + {scale1[16], {15{~scale1[16]}}})>>>16;

  //   ------------------ Section 1 ------------------

  assign typeconvert1 = (a1sum1[29:0] + {a1sum1[14], {13{~a1sum1[14]}}})>>>14;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1[0] <= 16'b0000000000000000;
        delay_section1[1] <= 16'b0000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= typeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1[15:0], 19'b0000000000000000000});

  assign a2mul1 = delay_section1[0] * coeff_a2_section1;

  assign a3mul1 = delay_section1[1] * coeff_a3_section1;

  assign b2mul1 = delay_section1[0] * coeff_b2_section1;

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{8{a2mul1[31]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a2sum1 = sub_temp[39:0];

  assign sub_cast_2 = a2sum1;
  assign sub_cast_3 = $signed({{8{a3mul1[31]}}, a3mul1});
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign a1sum1 = sub_temp_1[39:0];

  assign b1multypeconvert1 = $signed({typeconvert1[15:0], 14'b00000000000000});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{8{b2mul1[31]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b2sum1 = add_temp[39:0];

  assign add_cast_2 = b2sum1;
  assign add_cast_3 = $signed({delay_section1[1][15:0], 14'b00000000000000});
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign b1sum1 = add_temp_1[39:0];

  assign section_result1 = (b1sum1[33:0] + {b1sum1[18], {17{~b1sum1[18]}}})>>>18;

  assign mul_temp_1 = section_result1 * scaleconst2;
  assign scale2 = $signed({{11{mul_temp_1[31]}}, mul_temp_1});

  assign scaletypeconvert2 = (scale2[31:0] + {scale2[16], {15{~scale2[16]}}})>>>16;

  //   ------------------ Section 2 ------------------

  assign typeconvert2 = (a1sum2[29:0] + {a1sum2[14], {13{~a1sum2[14]}}})>>>14;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section2
      if (reset == 1'b1) begin
        delay_section2[0] <= 16'b0000000000000000;
        delay_section2[1] <= 16'b0000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section2[1] <= delay_section2[0];
          delay_section2[0] <= typeconvert2;
        end
      end
    end // delay_process_section2

  assign inputconv2 = $signed({scaletypeconvert2[15:0], 19'b0000000000000000000});

  assign a2mul2 = delay_section2[0] * coeff_a2_section2;

  assign a3mul2 = delay_section2[1] * coeff_a3_section2;

  assign b2mul2 = delay_section2[0] * coeff_b2_section2;

  assign sub_cast_4 = inputconv2;
  assign sub_cast_5 = $signed({{8{a2mul2[31]}}, a2mul2});
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign a2sum2 = sub_temp_2[39:0];

  assign sub_cast_6 = a2sum2;
  assign sub_cast_7 = $signed({{8{a3mul2[31]}}, a3mul2});
  assign sub_temp_3 = sub_cast_6 - sub_cast_7;
  assign a1sum2 = sub_temp_3[39:0];

  assign b1multypeconvert2 = $signed({typeconvert2[15:0], 14'b00000000000000});

  assign add_cast_4 = b1multypeconvert2;
  assign add_cast_5 = $signed({{8{b2mul2[31]}}, b2mul2});
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign b2sum2 = add_temp_2[39:0];

  assign add_cast_6 = b2sum2;
  assign add_cast_7 = $signed({delay_section2[1][15:0], 14'b00000000000000});
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign b1sum2 = add_temp_3[39:0];

  assign output_typeconvert = ({{5{b1sum2[39]}}, b1sum2[39:0]} + {b1sum2[29], {28{~b1sum2[29]}}})>>>29;

  // Assignment Statements
  assign filter_out = output_typeconvert;
endmodule  // filter
