// -------------------------------------------------------------
//
// Module: filter_lpf
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2026-07-30 18:10:59
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: /home/zcao/cz/matlab/baf4p1/LPF
// EDAScriptGeneration: off
// Name: filter_lpf
// ResetAssertedLevel: Active-low
// SerialPartition: 28
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully Serial
// Folding Factor        : 28
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 28
// Stable            : Yes
// Linear Phase      : Yes (Type 2)
// Arithmetic        : fixed
// Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
// Input             : s17,16 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s17,16 -> [-1 1)
//   Product         : s34,32 -> [-2 2)
//   Accumulator     : s35,32 -> [-4 4)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------
// Multipliers           : 1



`timescale 1 ns / 1 ns

module filter_lpf
               (
                clk,
                clk_enable,
                sign_en,
                bypass,
//                lpf_data_valid,
                o_cnt,
                coeffs,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   sign_en;
  input   bypass;
  input   signed [15:0] coeffs[27:0];


//  output       lpf_data_valid;
  output [4:0] o_cnt;

  input   signed [15:0] filter_in; //sfix17_En16
  output  signed [15:0] filter_out; //sfix17_En16

////////////////////////////////////////////////////////////////
//Module Architecture: filter_lpf
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
 wire signed [15:0] coeff1 ;
 wire signed [15:0] coeff2 ;
 wire signed [15:0] coeff3 ;
 wire signed [15:0] coeff4 ;
 wire signed [15:0] coeff5 ;
 wire signed [15:0] coeff6 ;
 wire signed [15:0] coeff7 ;
 wire signed [15:0] coeff8 ;
 wire signed [15:0] coeff9 ;
 wire signed [15:0] coeff10;
 wire signed [15:0] coeff11;
 wire signed [15:0] coeff12;
 wire signed [15:0] coeff13;
 wire signed [15:0] coeff14;
 wire signed [15:0] coeff15;
 wire signed [15:0] coeff16;
 wire signed [15:0] coeff17;
 wire signed [15:0] coeff18;
 wire signed [15:0] coeff19;
 wire signed [15:0] coeff20;
 wire signed [15:0] coeff21;
 wire signed [15:0] coeff22;
 wire signed [15:0] coeff23;
 wire signed [15:0] coeff24;
 wire signed [15:0] coeff25;
 wire signed [15:0] coeff26;
 wire signed [15:0] coeff27;
 wire signed [15:0] coeff28;

assign coeff1  =  coeffs[0];
assign coeff2  =  coeffs[1];
assign coeff3  =  coeffs[2];
assign coeff4  =  coeffs[3];
assign coeff5  =  coeffs[4];
assign coeff6  =  coeffs[5];
assign coeff7  =  coeffs[6]; 
assign coeff8  =  coeffs[7];
assign coeff9  =  coeffs[8];
assign coeff10 =  coeffs[9];
assign coeff11 =  coeffs[10];
assign coeff12 =  coeffs[11];
assign coeff13 =  coeffs[12];
assign coeff14 =  coeffs[13];
assign coeff15 =  coeffs[14];
assign coeff16 =  coeffs[15];
assign coeff17 =  coeffs[16];
assign coeff18 =  coeffs[17];
assign coeff19 =  coeffs[18];
assign coeff20 =  coeffs[19];
assign coeff21 =  coeffs[20];
assign coeff22 =  coeffs[21];
assign coeff23 =  coeffs[22];
assign coeff24 =  coeffs[23];
assign coeff25 =  coeffs[24];
assign coeff26 =  coeffs[25];
assign coeff27 =  coeffs[26];
assign coeff28 =  coeffs[27];











  // Signals
  reg  [4:0] cur_count; // ufix5
  wire phase_27; // boolean
  wire phase_0; // boolean
  reg  signed [16:0] delay_pipeline [0:27] ; // sfix17_En16
  wire signed [16:0] inputmux_1; // sfix17_En16
  reg  signed [34:0] acc_final; // sfix35_En32
  reg  signed [34:0] acc_out_1; // sfix35_En32
  wire signed [33:0] product_1; // sfix34_En32
  wire signed [15:0] product_1_mux; // sfix16_En16
  wire signed [32:0] mul_temp; // sfix33_En32
  wire signed [34:0] prod_typeconvert_1; // sfix35_En32
  wire signed [34:0] acc_sum_1; // sfix35_En32
  wire signed [34:0] acc_in_1; // sfix35_En32
  wire signed [34:0] add_signext; // sfix35_En32
  wire signed [34:0] add_signext_1; // sfix35_En32
  wire signed [35:0] add_temp; // sfix36_En32
  wire signed [16:0] output_typeconvert; // sfix17_En16
  reg  signed [16:0] output_register; // sfix17_En16

  // Block Statements
  always @ (posedge clk or negedge reset)
    begin: Counter_process
      if (reset == 1'b0) begin
        cur_count <= 5'b11011;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 5'b11011) begin
            cur_count <= 5'b00000;
          end
          else begin
            cur_count <= cur_count + 5'b00001;
          end
        end
      end
    end // Counter_process

  assign  phase_27 = (cur_count == 5'b11011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_0 = (cur_count == 5'b00000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @( posedge clk or negedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b0) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
      end
      else begin
        if (phase_27 == 1'b1) begin
          delay_pipeline[0] <= ~sign_en?  $signed({1'b0,filter_in})-17'sh0_80_00 : {{2{filter_in[15]}},filter_in[14:0]};
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
        end
      end
    end // Delay_Pipeline_process


  assign inputmux_1 = (cur_count == 5'b00000) ? delay_pipeline[0] :
                     (cur_count == 5'b00001) ? delay_pipeline[1] :
                     (cur_count == 5'b00010) ? delay_pipeline[2] :
                     (cur_count == 5'b00011) ? delay_pipeline[3] :
                     (cur_count == 5'b00100) ? delay_pipeline[4] :
                     (cur_count == 5'b00101) ? delay_pipeline[5] :
                     (cur_count == 5'b00110) ? delay_pipeline[6] :
                     (cur_count == 5'b00111) ? delay_pipeline[7] :
                     (cur_count == 5'b01000) ? delay_pipeline[8] :
                     (cur_count == 5'b01001) ? delay_pipeline[9] :
                     (cur_count == 5'b01010) ? delay_pipeline[10] :
                     (cur_count == 5'b01011) ? delay_pipeline[11] :
                     (cur_count == 5'b01100) ? delay_pipeline[12] :
                     (cur_count == 5'b01101) ? delay_pipeline[13] :
                     (cur_count == 5'b01110) ? delay_pipeline[14] :
                     (cur_count == 5'b01111) ? delay_pipeline[15] :
                     (cur_count == 5'b10000) ? delay_pipeline[16] :
                     (cur_count == 5'b10001) ? delay_pipeline[17] :
                     (cur_count == 5'b10010) ? delay_pipeline[18] :
                     (cur_count == 5'b10011) ? delay_pipeline[19] :
                     (cur_count == 5'b10100) ? delay_pipeline[20] :
                     (cur_count == 5'b10101) ? delay_pipeline[21] :
                     (cur_count == 5'b10110) ? delay_pipeline[22] :
                     (cur_count == 5'b10111) ? delay_pipeline[23] :
                     (cur_count == 5'b11000) ? delay_pipeline[24] :
                     (cur_count == 5'b11001) ? delay_pipeline[25] :
                     (cur_count == 5'b11010) ? delay_pipeline[26] :
                     delay_pipeline[27];

  //   ------------------ Serial partition # 1 ------------------

  assign product_1_mux = (cur_count == 5'b00000) ? coeff1 :
                        (cur_count == 5'b00001) ? coeff2 :
                        (cur_count == 5'b00010) ? coeff3 :
                        (cur_count == 5'b00011) ? coeff4 :
                        (cur_count == 5'b00100) ? coeff5 :
                        (cur_count == 5'b00101) ? coeff6 :
                        (cur_count == 5'b00110) ? coeff7 :
                        (cur_count == 5'b00111) ? coeff8 :
                        (cur_count == 5'b01000) ? coeff9 :
                        (cur_count == 5'b01001) ? coeff10 :
                        (cur_count == 5'b01010) ? coeff11 :
                        (cur_count == 5'b01011) ? coeff12 :
                        (cur_count == 5'b01100) ? coeff13 :
                        (cur_count == 5'b01101) ? coeff14 :
                        (cur_count == 5'b01110) ? coeff15 :
                        (cur_count == 5'b01111) ? coeff16 :
                        (cur_count == 5'b10000) ? coeff17 :
                        (cur_count == 5'b10001) ? coeff18 :
                        (cur_count == 5'b10010) ? coeff19 :
                        (cur_count == 5'b10011) ? coeff20 :
                        (cur_count == 5'b10100) ? coeff21 :
                        (cur_count == 5'b10101) ? coeff22 :
                        (cur_count == 5'b10110) ? coeff23 :
                        (cur_count == 5'b10111) ? coeff24 :
                        (cur_count == 5'b11000) ? coeff25 :
                        (cur_count == 5'b11001) ? coeff26 :
                        (cur_count == 5'b11010) ? coeff27 :
                        coeff28;
  assign mul_temp = inputmux_1 * product_1_mux;
  assign product_1 = $signed({{1{mul_temp[32]}}, mul_temp});

  assign prod_typeconvert_1 = $signed({{1{product_1[33]}}, product_1});

  assign add_signext = prod_typeconvert_1;
  assign add_signext_1 = acc_out_1;
  assign add_temp = add_signext + add_signext_1;
  assign acc_sum_1 = add_temp[34:0];

  assign acc_in_1 = (phase_0 == 1'b1) ? prod_typeconvert_1 :
                   acc_sum_1;

  always @ (posedge clk or negedge reset)
    begin: Acc_reg_1_process
      if (reset == 1'b0) begin
        acc_out_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          acc_out_1 <= acc_in_1;
        end
      end
    end // Acc_reg_1_process

  always @ (posedge clk or negedge reset)
    begin: Finalsum_reg_process
      if (reset == 1'b0) begin
        acc_final <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          acc_final <= acc_out_1;
        end
      end
    end // Finalsum_reg_process

  assign output_typeconvert = (acc_final[32:0] + {acc_final[16], {15{~acc_final[16]}}})>>>16;

  always @ (posedge clk or negedge reset)
    begin: Output_Register_process
      if (reset == 1'b0) begin
        output_register <= 0;
      end
      else begin
        if (phase_27 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
//assign lpf_data_valid = phase_27;
assign o_cnt          = cur_count;

   wire [23:0] output_register_temp; 
 assign output_register_temp = (output_register[16:15]==2'b10)? 16'h8000 : (output_register[16:15]==2'b01)? 16'h7fff : output_register[15:0];
 assign filter_out = bypass? filter_in : ~sign_en? output_register_temp[15:0] + 16'h8000 : output_register_temp[15:0];


endmodule  // filter_lpf
