set_attribute -type boolean [get_pins u_top_dig/flash_ctrl_top_inst/u_32k/TM0VPP] is_pad true
set_attribute -type boolean [get_pins u_iopad_plvpp/VPP] is_pad true
set_attribute -type boolean [get_pins u_iopad_testmode1/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_testmode0/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_exresetn/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_18_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_17_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_16_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_15_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_14_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_13_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_12_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_11_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_10_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_9_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_8_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_7_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_6_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_5_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_4_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_3_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_2_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_1_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_gpio_0_/P] is_pad true
set_attribute -type boolean [get_pins u_iopad_plar/P] is_pad true
